import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "momodo",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div>성공?</div>
    </>
  );
}
